baseurl = "http://ekhco.github.io"
title = "Eric Chow"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Eric Chow"
<<<<<<< HEAD
  description = 'Radiologist &bull; Stanford Healthcare  <p> I am a radiology resident and former biostatitician from Stanford. I spend my free time rock climbing, I also volunteer in Mountain Search and Rescue.</p>'
=======
  description = 'Radiologist &bull; Stanford Healthcare  <p> I am a medical student in Chicago and former biostatitician from Stanford with 8+ years of experience. I spend my free time rock climbing, I also volunteer in Mountain Search and Rescue.</p>'
>>>>>>> 7dffc7ac8ab56def1dfb24e167d6632879208027
  logo = ""
copyright = "Eric Chow 2020. Photo courtesy of Simon Fox"

