baseurl = "http://ekhco.github.io"
title = "Eric Chow"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Eric Chow"
  description = 'Radiologist &bull; Stanford Healthcare  <p> I am a radiology resident and former biostatitician from Stanford. I spend my free time rock climbing, I also volunteer in Mountain Search and Rescue.</p>'
  logo = ""
copyright = "Eric Chow 2020. Photo courtesy of Simon Fox"

