baseurl = "http://ekhco.github.io"
title = "Eric Chow"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Eric Chow"
  description = 'Medical Student & Data Scientist &bull; Chicago Medical School  <p> I am a data-scientist turned med-student with 8+ years of experience in biostatitics and research. I was a biostatistician at Stanford prior to starting med school. My ambition is to become some kind of physician-data-scientist and to save and improve lives with math and medicine. I also climb rock and ice and do mountain Search and Rescue on my weekends and free-time.</p>'
  logo = ""
copyright = "Eric Chow 2019"


[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "http://www.instagram.com/ericlimbs"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "http://www.github.com/ekhco"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/erickhchow/"
