baseurl = "http://ekhco.github.io"
title = "Eric Chow"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Eric Chow"
  description = 'Medical Student & Data Scientist &bull; Chicago Medical School  <p> I am a data-scientist turned med-student with 8+ years of experience in biostatitics and research. I was a biostatistician at Stanford prior to starting med school for 2+ years. My ambitions are to become some kind of physician-data-scientist so I can save and improve lives with math and medicine. I also rock climb and volunteer in mountain Search and Rescue.</p>'
  logo = ""
copyright = "Eric Chow 2019"


[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "http://www.instagram.com/ericlimbs"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "http://www.github.com/ekhco"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/erickhchow/"
