baseurl = "http://ekhco.github.io"
title = "Eric Chow"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Eric Chow"
  description = 'Medical Student & Data Scientist &bull; Chicago Medical School  <p> I am a medical student in Chicago and former biostatitician from Stanford with 8+ years of experience. I spend my free time rock climbing, I also volunteer in Mountain Search and Rescue.</p>'
  logo = ""
copyright = "Eric Chow 2020"

