baseurl = "http://ekhco.github.io"
title = "Eric Chow"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Eric Chow"
  description = 'Biostatistician &bull; Stanford University  <p> I am a healthcare data scientist with 6+ years of experience in academic medical research. My ambitions are to use data, algorithms, and statistics to increase our understanding of medicine, and ultimately to improve and save lives.</p>'
  logo = ""
  copyright = "Eric Chow 2017"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "http://www.instagram.com/erickhc8"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "http://www.github.com/ekhco"
  
[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/erickhchow/"
  
